services:
  db:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: roothamid123
      MARIADB_USER: hm
      MARIADB_PASSWORD: hamid123
      MARIADB_DATABASE: metrica
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: hm
      PMA_PASSWORD: hamid123
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/valori
    command: ["php-fpm"]
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
  caddy:
    image: caddy:latest
    depends_on:
      - app
    ports:
      - "2345:80"      # HTTP pour local
    environment:
      SITE_HOST: ${SITE_HOST:-localhost}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./:/valori
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  db_data:
  caddy_data:
  caddy_config: